<a href="https://colab.research.google.com/github/yoonhyunbin/pythonBDA/blob/main/BDA/03_NumPy_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy 활용

###Numpy 기초 함수들

##중요
ndarray.shape :배열의차원을나타내는튜플.각차원의크기를표현<br>
ndarray.ndim  :배열의차원수<br>
ndarray.size  :배열의총요소수<br>
ndarray.dtype :배열요소의데이터형식<br>
ndarray.itemsize :배열의각요소의크기(바이트)<br>
ndarray.nbytes   :배열의전체크기(바이트)<br>
ndarray.data     :배열요소를실제로포함하고있는버퍼의시작위치<br>

In [ ]:
import numpy as np #ndarry 여러 개의 값을 한 번에 저장하는 자료형

a = np.ndarray((2, 3))
print(a
      )
a = np.ndarray((3, 2), dtype = int)
print(a)

a = np.ndarray((3, 2), int)
print(a)

[[7.68128064e-316 0.00000000e+000 5.78415695e-317]
 [6.87159252e-310 6.87161314e-310 6.87161908e-310]]
[[      155470851               0]
 [       11707264 139082581074224]
 [139082998370000 139083118521392]]
[[      155470851               0]
 [       11707264 139082581074224]
 [139082998370000 139083118521392]]


In [ ]:
import numpy as np
b = np.array([1, 2, 3], dtype=int)
b

type(b)

print(b.shape)
print(b.ndim)
print(b.dtype)

print(b.size)
print(b.itemsize)
print(b.nbytes)

(3,)
1
int64
3
8
24


In [ ]:
import numpy as np

print(np.arange(3)) #range에서 실수도 포합 가능 = arange
print(np.arange(3, 7))
print(np.arange(3, 7, 2))

print(np.arange(2.0))
print(np.arange(2.0, 6.5))
print(np.arange(2.0, 6.5, 0.8))

[0 1 2]
[3 4 5 6]
[3 5]
[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


In [ ]:
import numpy as np

a = np.arange(12).reshape(3, 4) #3행 4열
print(a)

print(np.reshape(a, (2, 6)))

np.reshape(a, (3, 5)) #차수에따라원소의수가맞지않으면오류

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


ValueError: cannot reshape array of size 12 into shape (3,5)

###linspace


In [ ]:
#start = 시작 값, stop = 끝 값, num =  생성할 점의 개수 (start-stop) / (num-1) = 0, 10, 6 = 10/5 = 2; 점의 간격 2
import numpy as np
print(np.linspace(2.0, 3.0)) #기본 num은 50개
print((3-2) / (50 - 1))
print(np.linspace(2.0, 3.0, retstep = True)) #num값을 보여줌
a = (np.linspace(2.0, 3.0, retstep = True))
print(a[1])

[2.         2.02040816 2.04081633 2.06122449 2.08163265 2.10204082
 2.12244898 2.14285714 2.16326531 2.18367347 2.20408163 2.2244898
 2.24489796 2.26530612 2.28571429 2.30612245 2.32653061 2.34693878
 2.36734694 2.3877551  2.40816327 2.42857143 2.44897959 2.46938776
 2.48979592 2.51020408 2.53061224 2.55102041 2.57142857 2.59183673
 2.6122449  2.63265306 2.65306122 2.67346939 2.69387755 2.71428571
 2.73469388 2.75510204 2.7755102  2.79591837 2.81632653 2.83673469
 2.85714286 2.87755102 2.89795918 2.91836735 2.93877551 2.95918367
 2.97959184 3.        ]
0.02040816326530612
(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 ,

In [ ]:
np.linspace(2.0, 3.0, endpoint=False, retstep = True) #endpoint 마지막값 stop값 삭제

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 np.float64(0.02))

###Numpy 주요 함수들


In [ ]:
a = np.zeros(5)
print(a)
a = np.zeros((2, 1))
print(a)

[0. 0. 0. 0. 0.]
[[0.]
 [0.]]


In [ ]:
a = np.ones(5)
print(a)
a = np.ones((2, 1))
print(a)

[1. 1. 1. 1. 1.]
[[1.]
 [1.]]


In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [2]:
import numpy as np
np.empty(3)
a = np.full((2, 3), 10)
print(a)
print(np.zeros_like(a))
print(np.ones_like(a))
print(np.full_like(a, 5))

[[10 10 10]
 [10 10 10]]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[5 5 5]
 [5 5 5]]


In [ ]:
import numpy as np
a = np.full((2, 3), 10) #(shape, fill_value = 이 값으로 채워 놓는다)
print(a)
print()
print(np.full((2, 3), (1, 2, 3))) #2행 3열 123으로
print()
print(np.full((3, 4), range(4)))
print()
print(np.full((4, 3), fill_value = np.arange(4).reshape(4, 1))) # fill_value값이 0~3 4행 1열이라 이걸로 4행 3열을 채움

[[10 10 10]
 [10 10 10]]

[[1 2 3]
 [1 2 3]]

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]

[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]


###NumPy  연산

In [ ]:
a = np.arange(3) #정수와 정수의 연산은 가능 정수와 실수의 연산은 불가능
print(a + 2)
print(a * 2)
print(a / 2)
print(a - 2)

[2 3 4]
[0 2 4]
[0.  0.5 1. ]
[-2 -1  0]


In [8]:
import numpy as np
a = np.arange(1, 7).reshape(2, 3)
b = np.full_like(a, [1, 2, 3])
print(a)
print()
print(b)
print()
print(a + b)
print(a - b)
print(a * b)
print(a  / b)

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [1 2 3]]

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [18]:
import numpy as np
a = np.array([[1, 2], [2, 2], [3, 2]])
b = np.ones([2, 1])
print(a)
print(b)
print()
print(a @ b)

[[1 2]
 [2 2]
 [3 2]]
[[1.]
 [1.]]

[[3.]
 [4.]
 [5.]]


In [4]:
import numpy as np

a = np.full((2, 3), [1, 2, 3])
print(a)
print()

b = np.full((3, 2), [2, 1])
print(b)
print()

print(a @ b)
print()

print(a.dot(b))
print()

print(b.dot(a))
print()

print(np.matmul(a, b))
print()

print(np.matmul(b, a))

[[1 2 3]
 [1 2 3]]

[[2 1]
 [2 1]
 [2 1]]

[[12  6]
 [12  6]]

[[12  6]
 [12  6]]

[[3 6 9]
 [3 6 9]
 [3 6 9]]

[[12  6]
 [12  6]]

[[3 6 9]
 [3 6 9]
 [3 6 9]]


In [ ]:
a = np.array(((10, 20), (5, 8), (1, 2)))
print(a.sum()) #모든 원수의 합
print(a.sum(axis = 0)) #열의 합
print(a.sum(axis = 1)) #행의 합

46
[16 30]


In [ ]:
a = np.array(((3, 5, 8) , (1, 2, 3)))
a.cumsum() #원소를 누적합 시킴

array([ 3,  8, 16, 17, 19, 22])

In [ ]:
import numpy as np

a = np.array([1, 4, 9])
print(a)
print()

b = np.full_like(a, 2)
print(b)
print()

print(np.add(a, b))
print()

print(np.divide(a, b))
print()

print(np.power(a, b))

[1 4 9]

[2 2 2]

[ 3  6 11]

[0.5 2.  4.5]

[ 1 16 81]


### 1차원 배열의 첨자와 슬라이싱

In [ ]:
import numpy as np

a = np.power(np.arange(10), 2)
a

print(a[3])
print(a[-2])

print(a[1:4])
print(a[-5:-1])

print(a[8:2:-1])
print(a[-1:-7:-1])

a[::-1]
a[::-2]

a[2:5] = -100
a

a[2:5] = [-5, -5, -5]
a

#a[2:5] = [-5, -5] #3개의 값에 2개를 넣으려니 오류
a

a[2:5] = -10
a

9
64
[1 4 9]
[25 36 49 64]
[64 49 36 25 16  9]
[81 64 49 36 25 16]


array([  0,   1, -10, -10, -10,  25,  36,  49,  64,  81])

### 2차원 배열 슬라이싱

In [ ]:
import numpy as np

a = np.arange(30).reshape(5, 6) #2차원은 (행,열)로만 보
print(a)

print(a[3])

print(a[-1])

print(a[-2, :])

print(a[-2, ])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[18 19 20 21 22 23]
[24 25 26 27 28 29]
[18 19 20 21 22 23]
[18 19 20 21 22 23]


In [ ]:
import numpy as np

a = np.arange(30).reshape(5, 6)
print(a)

print(a[2:4])

print(a[1:5:2]) #

# print(a[, 1])  # 행을 비우면 오류

print(a[:, 1])

print(a[:, 1:6])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 6  7  8  9 10 11]
 [18 19 20 21 22 23]]
[ 1  7 13 19 25]
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]
 [25 26 27 28 29]]


In [ ]:
import numpy as np

a = np.arange(30).reshape(5, 6)
print(a)

print(a[:, ::2])

print(a[2, 4])

print(a[2][4])

print(a[1:3, 2:5])

print(a[:, :])

print(a[:, ])

print(a[:])

print(a[::-1, ::-1])

print(a[:-1, :-1])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]
 [24 26 28]]
16
16
[[ 8  9 10]
 [14 15 16]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[[29 28 27 26 25 24]
 [23 22 21 20 19 18]
 [17 16 15 14 13 12]
 [11 10  9  8  7  6]
 [ 5  4  3  2  1  0]]
[[ 0  1  2  3  4]
 [ 6  7  8  9 10]
 [12 13 14 15 16]
 [18 19 20 21 22]]


### 3차원 배열

In [ ]:
a = np.arange(24).reshape(2, 3, 4 ) #내가 느끼는건 그냥 (단원,행,열) 이렇게 보고 푸는게 쉽다.
print(a)
print()
print(a[1])
print()
print(a[:, 1])
print()
print(a[:, 1, 1])
print()
print(a[:, :, 1])
print()
print(a[..., 1]) #a[:, :, 1]이랑 동일
print()
print(a[1, ..., 1])
print()
print(a[0])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[ 4  5  6  7]
 [16 17 18 19]]

[ 5 17]

[[ 1  5  9]
 [13 17 21]]

[[ 1  5  9]
 [13 17 21]]

[13 17 21]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### 배열 관련 함수들

In [ ]:
import numpy as np

a = np.arange(12).reshape(2, 3, 2)
print(a)

b = a.ravel()
b

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
import numpy as np

a = np.arange(1, 7).reshape(2, 3)
print(a)
print()
print(np.transpose(a)) #행과 열을 바꿔버림

print(a.transpose())

print(a.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
import numpy as np

b = np.arange(1, 13).reshape(3, 2, 2)
print(b)
print(".......................")
print(b.T) #3차원은 (0,0,1) = (1,0,0) and (1,1,0) = (0,1,1) 로 바꿈

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
.......................
[[[ 1  5  9]
  [ 3  7 11]]

 [[ 2  6 10]
  [ 4  8 12]]]


In [20]:
import numpy as np

x = np.array([[7, 8, 9]])
print(x)
print()

y = np.swapaxes(x, 0, 1)
print(y)
print()

y = np.swapaxes(x, 1, 0)
print(y)
print()

y[0, 0] = 10
print(x)

[[7 8 9]]

[[7]
 [8]
 [9]]

[[7]
 [8]
 [9]]

[[10  8  9]]


In [21]:
import numpy as np

x = np.array(np.arange(8).reshape(2, 2, 2))
print(x)
print()

print(np.swapaxes(x, 0, 2))
print()

print(np.transpose(x, (2, 1, 0)))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]

[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


In [ ]:
import numpy as np

org = np.arange(5)
print(org)
print()

v = org.view()
print(v)
print()

v[2] = 200
print(v)
print()

print(org)

In [25]:
import numpy as np

org = np.arange(5)
print(org)
print()

c = org.copy()
print(c)
print()

c[2] = 200
print(c)
print()

print(org)

print(org.base) #배열이 뷰랑 복사본인지 확인 가능 none값 출력

[0 1 2 3 4]

[0 1 2 3 4]

[  0   1 200   3   4]

[0 1 2 3 4]
None


##브로드캐스팅

In [ ]:
from numpy import arange #열과 열을 연산하는데 개수가 틀리면 진행x 행 과 열은 노 상관

x = arange(1, 10).reshape(3, 3)
print(x)

y = arange(-1, 2)
print(y)

print(x * y)

print(x + y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[-1  0  1]
[[-1  0  3]
 [-4  0  6]
 [-7  0  9]]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [ ]:
import numpy as np
from numpy import arange

x = arange(1, 10).reshape(3, 3)
print(x)

y = arange(3, 10, 3).reshape(3, 1)
print(y)

# 소수점 이하 자릿수를 2자리로 설정
np.set_printoptions(precision=2)

print(x / y)

print(x - y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3]
 [6]
 [9]]
[[0.33 0.67 1.  ]
 [0.67 0.83 1.  ]
 [0.78 0.89 1.  ]]
[[-2 -1  0]
 [-2 -1  0]
 [-2 -1  0]]


In [ ]:
import numpy as np
from numpy import arange

x = arange(1, 4)
print(x)

y = arange(1, 4).reshape(3, 1)
print(y)

print(x * y)

print(x / y)

[1 2 3]
[[1]
 [2]
 [3]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]
[[1.   2.   3.  ]
 [0.5  1.   1.5 ]
 [0.33 0.67 1.  ]]


In [ ]:
import numpy as np
from numpy import array

x = array([0, 10, 20, 30])
print(x)

print(np.newaxis is None)

# 차수를 증가 1차원을 2차원으로
a = x[None, :]
print(a)

a = x[np.newaxis, :] #열 진행
print(a)

a = x[:, np.newaxis] #행 진행
print(a)

print(a.shape)

[ 0 10 20 30]
True
[[ 0 10 20 30]]
[[ 0 10 20 30]]
[[ 0]
 [10]
 [20]
 [30]]
(4, 1)


In [26]:
from numpy import array
import numpy as np

x = array([0, 10, 20, 30])
a = x[:, np.newaxis]
b = array([1, 2, 3])

print(a)
print()
print(b)
print()
print(a + b)
print()
print(a * b)

[[ 0]
 [10]
 [20]
 [30]]

[1 2 3]

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]

[[ 0  0  0]
 [10 20 30]
 [20 40 60]
 [30 60 90]]


In [31]:
import numpy as np
a = np.arange(0, 31, 10).reshape(4, 1)
b = array((1, 2, 3))
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

##고급 색인

In [ ]:
import numpy as np
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(x[1])
print(x[:5])
print(x[[2]])
print(x[[2,3]])

1
[0 1 2 3 4]
[2]
[2 3]


In [ ]:
from numpy import arange
x = arange(56).reshape(7, 8)
print(x[0])
print(x[0,1])
print()
print(x[:, 2:8])
print()
print(x[..., 2:8]) #x[, 2:8] 안됨

[0 1 2 3 4 5 6 7]
1

[[ 2  3  4  5  6  7]
 [10 11 12 13 14 15]
 [18 19 20 21 22 23]
 [26 27 28 29 30 31]
 [34 35 36 37 38 39]
 [42 43 44 45 46 47]
 [50 51 52 53 54 55]]

[[ 2  3  4  5  6  7]
 [10 11 12 13 14 15]
 [18 19 20 21 22 23]
 [26 27 28 29 30 31]
 [34 35 36 37 38 39]
 [42 43 44 45 46 47]
 [50 51 52 53 54 55]]


In [ ]:
#x[0,1] / x[[0], [1]] 다름
print(x[[0], [1]]) #0행의 1열 값
print()
print(x[[0, 1]]) #0부터 1행까지
print()
print(x[:, [5, 4]]) # : 와 열 안의 ,와 헷갈리지 말기
print(0)
print(x[[1, 3]])
print()
print(x[[1, 3], :])

[1]

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]

[[ 5  4]
 [13 12]
 [21 20]
 [29 28]
 [37 36]
 [45 44]
 [53 52]]
0
[[ 8  9 10 11 12 13 14 15]
 [24 25 26 27 28 29 30 31]]

[[ 8  9 10 11 12 13 14 15]
 [24 25 26 27 28 29 30 31]]


In [ ]:
import numpy as np

x = np.arange(56).reshape(7, 8)
print(x)

# 첨자 [1, 2]과 [3, 2]에 해당하는 값 10과 26
print(x[[1, 3], [2, 2]])

# 위와 동일
print(x[[1, 3], [2]])

# 1, 3행의 2열
print(x[[1, 3], 2])

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]]
[10 26]
[10 26]
[10 26]


In [ ]:
from numpy import arange, array

x = arange(56).reshape(7, 8)
print(x)
print()
print(x[array([0, 2, 4]), 1])
print()
print(x[0, 1])
print()
print(x[2, 1])
print()
print(x[4, 1])
print()

print(x[array([0, 2, 4]), :2])

#print(x[array([0, 2, 4]), array([0, 1])]) 오류

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]]

[ 1 17 33]

1

17

33

[[ 0  1]
 [16 17]
 [32 33]]
[ 0 17 34]


In [ ]:
from numpy import arange

a = arange(40).reshape(5, 8)
print(a)
print()

print(a[arange(2, 4)][:, [1, 0]])
print()

print(a[arange(2, 5)][:, [1, 0, 3, 5]])
print()

print(a[arange(2, 5)])
print()

print(a[arange(2, 5)][:, arange(-1, -8, -1)])

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]]

[[17 16]
 [25 24]]

[[17 16 19 21]
 [25 24 27 29]
 [33 32 35 37]]

[[16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]]

[[23 22 21 20 19 18 17]
 [31 30 29 28 27 26 25]
 [39 38 37 36 35 34 33]]
