<a href="https://colab.research.google.com/github/yoonhyunbin/pythonBDA/blob/main/BDA/04w_array_stack_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Vstack()

In [11]:
import numpy as np

a = np.arange(6).reshape(3, 2)
print(a)

print()

b = np.arange(6, 12).reshape(3, 2)
print(b)

print()

print(np.vstack((a, b)))

x = np.array([1, 2, 3])
print(x)

print()

y = np.array([5, 6, 7])
print(y)

print()

print(np.vstack((x, y)))

[[0 1]
 [2 3]
 [4 5]]

[[ 6  7]
 [ 8  9]
 [10 11]]

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[1 2 3]

[5 6 7]

[[1 2 3]
 [5 6 7]]


###Hstack()

In [12]:
import numpy as np #hstack 1차원 1차원 합치면 2차원 vstack 1차원 1차원 합치면 2차원

a = np.arange(6).reshape(3, 2)
print(a)

print()  # 공백 한 줄

b = np.arange(10, 19).reshape(3, 3)
print(b)

print()  # 공백 한 줄

print(np.hstack((a, b)))

print()  # 공백 한 줄

x = np.arange(3)
print(x)

print()  # 공백 한 줄

y = np.arange(10, 15)
print(y)

print()  # 공백 한 줄

print(np.hstack((x, y)))

[[0 1]
 [2 3]
 [4 5]]

[[10 11 12]
 [13 14 15]
 [16 17 18]]

[[ 0  1 10 11 12]
 [ 2  3 13 14 15]
 [ 4  5 16 17 18]]

[0 1 2]

[10 11 12 13 14]

[ 0  1  2 10 11 12 13 14]


### Column_stack


In [13]:
import numpy as np

x = np.array([1, 2, 3])
print(x)

print()  # 공백 한 줄

y = np.array([10, 20, 30])
print(y)

print()  # 공백 한 줄

print(np.column_stack((x, y)))

print()  # 공백 한 줄

print(np.column_stack((x[:, np.newaxis], y[:, np.newaxis])))

print()  # 공백 한 줄

print(x[:, np.newaxis])

print()  # 공백 한 줄

print(np.hstack((x, y)))

print()  # 공백 한 줄

print(np.column_stack == np.hstack)

[1 2 3]

[10 20 30]

[[ 1 10]
 [ 2 20]
 [ 3 30]]

[[ 1 10]
 [ 2 20]
 [ 3 30]]

[[1]
 [2]
 [3]]

[ 1  2  3 10 20 30]

False


###Row_stack은 Vstack과 똑같은 결과 하지만 row_stack는 사라질 예정이라 쓰지 말고 그렇구나 하기

###concatennate()

In [14]:
#1차원
import numpy as np

a = np.array([1, 2])
print(a)

print()

b = np.array([3, 4])
print(b)

print()

c = np.array([5, 6])
print(c)

print()

print(np.concatenate((a, b, c)))

print()
print(np.concatenate((a, b, c), axis=0))

print()

print(np.concatenate((a, b, c), axis=None))

#2차원 concatennate() =  axis값을 안 넣으면 0값임 이게 0값이면 vstack처럼 나오고 값이 1이면 hstack결과가 나옴 None는 평탄화 hstack하고 비슷한거 같지만 다름 2차원을 1차원으로 hstack처럼 해버릴수 있
x = np.arange(6).reshape(2, 3)
print(x)

print()

y = np.arange(10, 16).reshape(2, 3)
print(y)

print()

z = np.arange(20, 24).reshape(2, 2)
print(z)

print()

print(np.concatenate((x, y)))

x = np.arange(6).reshape(2, 3)
print(x)

print()

y = np.arange(10, 16).reshape(2, 3)
print(y)

print()

z = np.arange(20, 24).reshape(2, 2)
print(z)

print()

print(np.concatenate((x, y), axis=1))

print()

print(np.concatenate((x, y, z), axis=1))

print()

print(np.concatenate((x, y), axis=None))

x = np.arange(6).reshape(2, 3)
print(x)

print()

y = np.arange(10, 16).reshape(2, 3)
print(y)

print()
z = np.arange(20, 24).reshape(2, 2)
print(z)

print()

print(np.concatenate((x, y), axis=1))

print()

print(np.concatenate((x, y, z), axis=1))

print()

print(np.concatenate((x, y), axis=None))

[1 2]

[3 4]

[5 6]

[1 2 3 4 5 6]

[1 2 3 4 5 6]

[1 2 3 4 5 6]
[[0 1 2]
 [3 4 5]]

[[10 11 12]
 [13 14 15]]

[[20 21]
 [22 23]]

[[ 0  1  2]
 [ 3  4  5]
 [10 11 12]
 [13 14 15]]
[[0 1 2]
 [3 4 5]]

[[10 11 12]
 [13 14 15]]

[[20 21]
 [22 23]]

[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]]

[[ 0  1  2 10 11 12 20 21]
 [ 3  4  5 13 14 15 22 23]]

[ 0  1  2  3  4  5 10 11 12 13 14 15]
[[0 1 2]
 [3 4 5]]

[[10 11 12]
 [13 14 15]]

[[20 21]
 [22 23]]

[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]]

[[ 0  1  2 10 11 12 20 21]
 [ 3  4  5 13 14 15 22 23]]

[ 0  1  2  3  4  5 10 11 12 13 14 15]


###np.stack()

In [15]:
import numpy as np

a = np.array([1, 2, 3])
print(a)

print()

b = np.array([4, 5, 6])
print(b)

print()

print(np.stack((a, b), axis=0)) #vstack

print()

print(np.stack((a, b), axis=1)) #column_stack

print()

a = np.array([1, 2, 3])
print(a)

print()

b = np.array([4, 5, 6])
print(b)

print()

print(np.stack((a, b)))

print()

print(np.stack((a, b), axis=1))

print()

print(np.stack((a, b), axis=-1))

[1 2 3]

[4 5 6]

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[1 2 3]

[4 5 6]

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


##3차원!!!!!



In [16]:
import numpy as np

a = np.arange(1, 19).reshape(3, 3, 2)
print(a)

print()

print(a.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]

(3, 3, 2)


###axis = 0

In [17]:
import numpy as np

x = np.arange(6).reshape(2, 3)
print(x)

print()

y = np.arange(10, 16).reshape(2, 3)
print(y)

print()

z = np.arange(20, 26).reshape(2, 3)
print(z)

print()

ax0 = np.stack((x, y, z), axis=0)
print(ax0)

print()

print(ax0.shape)

[[0 1 2]
 [3 4 5]]

[[10 11 12]
 [13 14 15]]

[[20 21 22]
 [23 24 25]]

[[[ 0  1  2]
  [ 3  4  5]]

 [[10 11 12]
  [13 14 15]]

 [[20 21 22]
  [23 24 25]]]

(3, 2, 3)


###axis = 1

In [18]:
import numpy as np

x = np.arange(6).reshape(2, 3)
print(x)

print()

y = np.arange(10, 16).reshape(2, 3)
print(y)

print()

z = np.arange(20, 26).reshape(2, 3)
print(z)

print()

ax1 = np.stack((x, y, z), axis=1)
print(ax1)

print()

print(ax1.shape)

[[0 1 2]
 [3 4 5]]

[[10 11 12]
 [13 14 15]]

[[20 21 22]
 [23 24 25]]

[[[ 0  1  2]
  [10 11 12]
  [20 21 22]]

 [[ 3  4  5]
  [13 14 15]
  [23 24 25]]]

(2, 3, 3)


###axis = 2

In [19]:
import numpy as np

x = np.arange(6).reshape(2, 3)
print(x)

print()

y = np.arange(10, 16).reshape(2, 3)
print(y)

print()

z = np.arange(20, 26).reshape(2, 3)
print(z)

print()

ax2 = np.stack((x, y, z), axis=2)
print(ax2)

print()

print(ax2.shape)

[[0 1 2]
 [3 4 5]]

[[10 11 12]
 [13 14 15]]

[[20 21 22]
 [23 24 25]]

[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]]

(2, 3, 3)


###np.stack (axis = 2)

In [20]:
import numpy as np

x = np.arange(6).reshape(2, 3)
print(x)

print()

y = np.arange(10, 16).reshape(2, 3)
print(y)

print()

z = np.arange(20, 26).reshape(2, 3)
print(z)

print()

print(x[:, :, np.newaxis])

print()

print(y[:, :, np.newaxis])

print()

print(z[:, :, np.newaxis])

print()

print(np.expand_dims(x, axis=2))

print()

print(np.expand_dims(y, axis=2))

print()

print(np.expand_dims(z, axis=2))

print()

ax2 = np.stack((x, y, z), axis=2)
print(ax2)

print()

print(ax2.shape)

[[0 1 2]
 [3 4 5]]

[[10 11 12]
 [13 14 15]]

[[20 21 22]
 [23 24 25]]

[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]

[[[10]
  [11]
  [12]]

 [[13]
  [14]
  [15]]]

[[[20]
  [21]
  [22]]

 [[23]
  [24]
  [25]]]

[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]

[[[10]
  [11]
  [12]]

 [[13]
  [14]
  [15]]]

[[[20]
  [21]
  [22]]

 [[23]
  [24]
  [25]]]

[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]]

(2, 3, 3)


##교수님과 같이 실습 시작 지점

In [30]:
import numpy as np
a = np.arange(1, 13).reshape(3, 4)

c = np.arange(1, 6, 2)

print(a)
print()
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[1 3 5]


In [32]:
import numpy as np
np.hstack((a, np.expand_dims(c, axis = 1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [29]:
np.column_stack((a, c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

###np.c_[] 개요

In [33]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.c_[a, b]
print(result)

[[1 4]
 [2 5]
 [3 6]]


In [34]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

###2차원으로

In [38]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])
print(x)
print()
print(y)

[[1 2 3]]

[[4 5 6]]


In [39]:
x.shape, y.shape

((1, 3), (1, 3))

In [40]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [41]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [42]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [43]:
np.column_stack((x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

###np.r_[] 개요

In [44]:
import numpy as np

a = np.array([1, 2, 3])
print(a)

print()

b = np.array([4, 5, 6])
print(b)

print()

print(np.r_[a, b])

print()

print(np.hstack((a, b)))

print()

print(np.row_stack((a, b)))

[1 2 3]

[4 5 6]

[1 2 3 4 5 6]

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]


/tmp/ipykernel_5296/2250121442.py:21: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((a, b)))


In [46]:
print(np.r_[a, 0, 0, b])

print()

print(np.r_[3:10:3, [0]*2, 5, 6])

print()

print(np.r_[-1:1:6j, [0]*2, 5, 6]) # (1 - (-1)) / (6 - 1) = 0.4칸 만큼 간격 6개 만듬

print()

print(np.linspace(-1, 1, 6))

[1 2 3 0 0 4 5 6]

[3 6 9 0 0 5 6]

[-1.  -0.6 -0.2  0.2  0.6  1.   0.   0.   5.   6. ]

[-1.  -0.6 -0.2  0.2  0.6  1. ]


In [47]:
import numpy as np

a = np.array([[0, 1, 2], [3, 4, 5]])
print(a)

print()

print(np.r_[a, a, a])

print()

print(np.r_['0', a, a])

print()

print(np.r_['-1', a, a])

print()

print(np.r_['1', a, a])

[[0 1 2]
 [3 4 5]]

[[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]

[[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]]

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]]


##배열 분리(np.split())

In [50]:
import numpy as np

x = np.arange(18).reshape(3, 6)
print(x)

print(np.split(x, 3, axis=0))

print()

print(np.split(x, (1, 2), axis=0))

print()

print(np.split(x, 3, axis=1))

print()

print(np.split(x, (2, 4), axis=1))

print()

print()

print(np.vsplit(x, 3))

print()

print(np.vsplit(x, (1, 2)))

print()

print(np.hsplit(x, 3))

print()

print(np.hsplit(x, (2, 4)))

print()


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]

[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]

[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]


[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]

[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]

[array([[ 0,  1],
       [ 6,  7],
       [12, 1

In [51]:
import numpy as np

x = np.arange(9.0)
print(x)

print()

s = np.split(x, 3)
print(s)

[0. 1. 2. 3. 4. 5. 6. 7. 8.]

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]


In [52]:
import numpy as np

y = np.arange(10, 61, 10)
print(y)

print()

print(np.split(y, [2, 3, 4, 6])) # [:2], [2:3], [3:4], [4:6], [6:]

print()

x = np.arange(1, 10)
print(x)

print()

print(np.split(x, [2, 6]))

[10 20 30 40 50 60]

[array([10, 20]), array([30]), array([40]), array([50, 60]), array([], dtype=int64)]

[1 2 3 4 5 6 7 8 9]

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]


In [53]:
import numpy as np

a = np.arange(24).reshape(2, 12)
print(a)

print()

print(np.hsplit(a, 3))

print()

print(np.split(a, 3, axis=1)) #여기서 axis는 내가 볼때 a값의 axis를 적용하는거 같

print()

print(np.split(a, 4, axis=1))

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]

[array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]]), array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]]), array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])]

[array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]]), array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]]), array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])]

[array([[ 0,  1,  2],
       [12, 13, 14]]), array([[ 3,  4,  5],
       [15, 16, 17]]), array([[ 6,  7,  8],
       [18, 19, 20]]), array([[ 9, 10, 11],
       [21, 22, 23]])]


In [54]:
import numpy as np

b = np.arange(24).reshape(6, 4)
print(b)

print()

print(np.split(b, 3, axis=0))

print()

print(np.split(b, [2, 4, 6], axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
       [20, 21, 22, 23]])]

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
       [20, 21, 22, 23]]), array([], shape=(0, 4), dtype=int64)]


In [55]:
import numpy as np

a = np.arange(24).reshape(2, 12)
print(a)

print()

print(np.split(a, [3, 5, 7], axis=1))

print()

b = np.arange(24).reshape(6, 4)
print(b)

print()

print(np.split(b, 3, axis=0))

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]

[array([[ 0,  1,  2],
       [12, 13, 14]]), array([[ 3,  4],
       [15, 16]]), array([[ 5,  6],
       [17, 18]]), array([[ 7,  8,  9, 10, 11],
       [19, 20, 21, 22, 23]])]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
       [20, 21, 22, 23]])]


###np.hsplit()

In [56]:
import numpy as np

a = np.arange(10)
print(a)

print()

print(np.hsplit(a, 2))

print()

print(np.hsplit(a, [2, 5]))

[0 1 2 3 4 5 6 7 8 9]

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]


In [57]:
import numpy as np

a = np.arange(24).reshape(2, 12)
print(a)

print()

print(np.hsplit(a, (3, 5, 8)))

print()

print(a[:, :3])

print()

print(a[:, 8:])

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]

[array([[ 0,  1,  2],
       [12, 13, 14]]), array([[ 3,  4],
       [15, 16]]), array([[ 5,  6,  7],
       [17, 18, 19]]), array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])]

[[ 0  1  2]
 [12 13 14]]

[[ 8  9 10 11]
 [20 21 22 23]]


###np.vsplit()

In [59]:
import numpy as np

a = np.arange(18).reshape(6, 3)
print(a)

print()

print(np.vsplit(a, 3))

print()

#print(np.vsplit(a, 4)) 행이 6개인데 4등분이 안 되시 떄문에 오

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]

[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]]), array([[12, 13, 14],
       [15, 16, 17]])]



In [58]:
import numpy as np

a = np.arange(18).reshape(6, 3)
print(a)

print()

print(np.vsplit(a, (1, 4, 6)))

print()

print(a[:1, :])

print()

print(a[4:6, :])

print()

print(a[6:, :])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]

[array([[0, 1, 2]]), array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]]), array([[12, 13, 14],
       [15, 16, 17]]), array([], shape=(0, 3), dtype=int64)]

[[0 1 2]]

[[12 13 14]
 [15 16 17]]

[]


###3차워 배열의 vsplit()

In [60]:
import numpy as np

x = np.arange(32).reshape(4, 4, 2)
print(x)

print()

print(np.vsplit(x, 2))

print()

print(np.split(x, 2, axis=0))

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]
  [30 31]]]

[array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]]), array([[[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])]

[array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]]), array([[[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])]


In [61]:
import numpy as np

x = np.arange(32).reshape(4, 4, 2)
print(x)

print()

print(np.vsplit(x, [1, 3]))

print()

print(x[:1, :, :])

print()

print(x[1:3, :, :])

print()

print(x[3:, :, :])

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]
  [30 31]]]

[array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]]), array([[[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]]), array([[[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])]

[[[0 1]
  [2 3]
  [4 5]
  [6 7]]]

[[[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]

[[[24 25]
  [26 27]
  [28 29]
  [30 31]]]


###3차원 배열의 hsplit()

In [62]:
import numpy as np

x = np.arange(32).reshape(4, 4, 2)
print(x)

print()

print(np.hsplit(x, 2))

print()

print(np.split(x, 2, axis=1))

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]
  [30 31]]]

[array([[[ 0,  1],
        [ 2,  3]],

       [[ 8,  9],
        [10, 11]],

       [[16, 17],
        [18, 19]],

       [[24, 25],
        [26, 27]]]), array([[[ 4,  5],
        [ 6,  7]],

       [[12, 13],
        [14, 15]],

       [[20, 21],
        [22, 23]],

       [[28, 29],
        [30, 31]]])]

[array([[[ 0,  1],
        [ 2,  3]],

       [[ 8,  9],
        [10, 11]],

       [[16, 17],
        [18, 19]],

       [[24, 25],
        [26, 27]]]), array([[[ 4,  5],
        [ 6,  7]],

       [[12, 13],
        [14, 15]],

       [[20, 21],
        [22, 23]],

       [[28, 29],
        [30, 31]]])]


In [63]:
import numpy as np

x = np.arange(32).reshape(4, 4, 2)
print(x)

print()

print(np.hsplit(x, [1, 3]))

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]
  [30 31]]]

[array([[[ 0,  1]],

       [[ 8,  9]],

       [[16, 17]],

       [[24, 25]]]), array([[[ 2,  3],
        [ 4,  5]],

       [[10, 11],
        [12, 13]],

       [[18, 19],
        [20, 21]],

       [[26, 27],
        [28, 29]]]), array([[[ 6,  7]],

       [[14, 15]],

       [[22, 23]],

       [[30, 31]]])]


##numpy의 난수와 다양한 함수

In [94]:
import numpy as np

rg = np.random.default_rng(12345)
rg.random() #[0, 1) 0과 1사이 = 0이상 1미

0.22733602246716966

In [88]:
rg.random()

0.3264728640701121

In [101]:
rg.random(5)

array([0.60162124, 0.93198836, 0.72478136, 0.86055132, 0.9293378 ])

In [102]:
rg.random((3, 4))

array([[0.54618601, 0.93767296, 0.49498794, 0.27377318],
       [0.45177871, 0.66503892, 0.33089093, 0.90345401],
       [0.25707418, 0.33982834, 0.2588534 , 0.35544648]])

In [103]:
rg.random((2, 3, 4))

array([[[0.00502233, 0.62860454, 0.28238271, 0.06808769],
        [0.61682898, 0.17632632, 0.30438839, 0.44088681],
        [0.15020234, 0.21792886, 0.47433312, 0.47636886]],

       [[0.25523235, 0.29756527, 0.27906712, 0.26057921],
        [0.48276159, 0.21197904, 0.4956306 , 0.24626133],
        [0.83848265, 0.18013059, 0.86215629, 0.17829944]]])

In [105]:
import numpy as np

rg = np.random.default_rng(1)
rg.integers(low = 0, high = 10, size = 3) #[0, 10) 정수 난수 3개

array([4, 5, 7])

In [106]:
rg.integers(0, 10, 3)

array([9, 0, 1])

In [107]:
rg.integers(0, 20, (3, 4))

array([[16, 18,  4,  6],
       [17,  8,  5, 16],
       [ 5,  8, 12, 10]])

In [108]:
rg.integers(1, 7, (3, 4))

array([[1, 1, 6, 5],
       [6, 4, 5, 2],
       [3, 5, 1, 2]])

In [110]:
import numpy as np

rg = np.random.default_rng(1)
rg.standard_normal(5) #표준 정규분포 실수 난수

array([ 0.34558419,  0.82161814,  0.33043708, -1.30315723,  0.90535587])

In [112]:
rg.standard_normal((3, 4))

array([[-0.29245675, -0.78190846, -0.25719224,  0.00814218],
       [-0.27560291,  1.29406381,  1.00672432, -2.71116248],
       [-1.88901325, -0.17477209, -0.42219041,  0.213643  ]])

#배열 결합 연습

In [117]:
a = np.arange(1, 4)
b = np.arange(4, 7)
c = np.arange(7, 10)
a, b, c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [116]:
p = np.arange(1, 7).reshape(2, 3)
q = np.arange(11, 17).reshape(2, 3)
r = np.arange(21, 27).reshape(2, 3)
p, q, r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [118]:
np.vstack((a, b, c))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [119]:
np.vstack((p, q, r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [120]:
np.hstack((a, b, c)) #1D -> 1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
np.hstack((p, q, r)) 2D -> 2D

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [125]:
a, b, c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [126]:
np.column_stack((a,b,c)) #1D -> 2D

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [128]:
np.column_stack((p, q, r)) #2D -> 2D

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [129]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
np.concatenate((a, b, c), axis = None)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
np.concatenate((a, b, c), axis = -1)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
np.concatenate((p, q, r))


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [142]:
np.concatenate((p, q, r), axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [134]:
np.concatenate((p, q, r), axis = 1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [143]:
np.concatenate((p, q, r), axis = -1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [141]:
np.concatenate((p, q, r), axis = None)

array([ 1,  2,  3,  4,  5,  6, 11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 25,
       26])

In [144]:
np.c_[a, b, c] #1D -> 2D

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [145]:
np.c_[p, q, r] #2D -> 2D

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [146]:
np.r_[a, b, c] #1D -> 1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [148]:
np.c_[p, q, r]

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])